title: Open Socialism
tagline: a compelling alternative to democratic capitalism
description: > # this means to ignore newlines until "baseurl:"
  a compelling alternative to democratic capitalism
baseurl: "" # the subpath of your site, e.g. /blog
analytics_id: UA-75947611-1
exclude: ['auto', 'support']
url: https://opensocialism.com

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

plugins:
- jekyll-include-cache

defaults:
-
  scope:
    path: ""
    type: "pages"
  values:
    layout: "page"
-
  scope:
    path: "societal-metrics"
    type: "pages"
  values:
    layout: "societal-metrics"
-
  scope:
    path: "assess-dc/*"
    type: "pages"
  values:
    layout: "assess-dc"
