title: Open Socialism
tagline: a compelling alternative to democratic capitalism
description: > # this means to ignore newlines until "baseurl:"
  a compelling alternative to democratic capitalism
baseurl: "" # the subpath of your site, e.g. /blog
analytics_id: UA-75947611-1
exclude: ['auto']
url: https://opensocialism.com

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

defaults:
-
  scope:
    path: ""
    type: "pages"
  values:
    layout: "page"
