variables:
  defaultImage: ubuntu-latest

jobs:
  - job: verify_html_links
    pool:
      vmImage: $(defaultImage)
    steps:
      - script: auto/verify/verify-html
        displayName: Verify html links


  - job: verify_spelling
    pool:
      vmImage: $(defaultImage)
    steps:
      - script: auto/verify/verify-spelling
        displayName: Check spelling


  - job: verify_yaml
    pool:
      vmImage: $(defaultImage)
    steps:
      - script: auto/verify/verify-yaml
        displayName: Lint yaml

  - job: verify_docker
    pool:
      vmImage: $(defaultImage)
    steps:
      - script: auto/verify/verify-docker
        displayName: Lint dockerfiles


  - job: verify_shell
    pool:
      vmImage: $(defaultImage)
    steps:
      - script: auto/verify/verify-shell
        displayName: Lint bash scripts
